### ISSUE TITLE
I cannot find 'camera_calibration.tar'

### ISSUE THREAD

**Issue by redorangeyellowy** [ATAboukhadra/THOR-Net#2]
https://github.com/ATAboukhadra/THOR-Net/blob/6e0d4283c835934e45a2f1e5613843d73cfb8c21/utils/h2o_utils/h2o_preprocessing_utils.py#L108

In this line, I cannot find `camera_calibration.tar` in h2o dataset and your repository.

How can I get this one?

**Comment by ATAboukhadra** [comment]
Hi,

The `camera_calibration.tar` includes the camera intrinsics of the samples.

Unfortunately, we converted the H2O dataset from its original format to .tar format in order to speed up training. So, many of the small files are now clustered in .tar files including the camera intrinsics inside the `camera_calibration.tar`. I can share with you the `camera_calibration.tar` -you can find it [here-](https://cloud.dfki.de/owncloud/index.php/s/BEnxydre2cL5zb2) but I assume you will find a similar error with other non-existing tar files that include the dataset files. 

Therefore, I suggest if you want to work with H2O on its raw format where files are normally distributed over directories that you change the data loader code in order to deal with the dataset in its original hierarchy. 

Kind regards,
Ahmed
